### ISSUE TITLE
ASM 4.1

### ISSUE THREAD

**Issue by analytically** [PROSPricing/jdk8patch-halfupround#2]
PlayFramework depends on ASM 4.1, so upgrading to that would be great! :-)

**Comment by wrprice** [comment]
Thanks for the feedback.  I'm looking at updating to ASM 5.x and will investigate whether it makes sense to stop at 4.x along the way.  Of course, if you care to contribute a pull request, that would probably speed things up a little.  :-)

**Comment by wrprice** [comment]
@analytically Actually, it turns out that it was easier and quicker than I expected.  Would you care to try the current head of the `asm4` branch?  That branch build depends on ASM 4.2 (latest 4.x in Maven Central at this time) but at runtime seemed to work on 4.0 and also 4.1.

**Comment by wrprice** [comment]
Fixed in `v1.4` by commit [7f0ef6bfb8](https://github.com/PROSPricing/jdk8patch-halfupround/commit/7f0ef6bfb86a5aa6e72f139636fd64504bc31412)
