### ISSUE TITLE
the 1.8.0_u40 "fix" doesn't work --- can we contact Oracle?

### ISSUE THREAD

**Issue by fommil** [PROSPricing/jdk8patch-halfupround#4]
Thanks for bringing this bug and workaround to everybody's attention.

I am using `Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b23)` which supposedly has a fix https://bugs.openjdk.java.net/browse/JDK-8061380 but I have a failing test case (this is scala but I'm sure you can translate to Java):

```scala
val f = new java.text.DecimalFormat("#,##0.000")
f.setRoundingMode(java.math.RoundingMode.HALF_UP)
f.format(1.2345) shouldEqual "1.235"
```

There seems to be absolutely no way to comment on the JIRA so I have no way to bring this to the attention of OpenJDK/Oracle.

Do you have any contact with the people performing the official fix? I'd like them to know that this is still failing.

**Comment by fommil** [comment]
perhaps olivier.lagneau at oracle.com ?

**Comment by fommil** [comment]
Turns out that although `1.2345.toString` gives `1.2345` this is not actually the representation used by BigDecimal... which I presume to be machine precision below `1.2345`. That means the rounding doesn't kick in. I guess this may well be considered "not a bug" by Java, but it certainly results in weird regressions in application code.

**Comment by wrprice** [comment]
@fommil - Yes, that's the inherent inaccuracy of the [IEEE 754 binary, 64-bit floating point representation][1].  In your code, the literal decimal value `1.2345` gets computed to the nearest _exact binary_ representation at compile time.  That exact value, back in decimal form, is:

    1.2344999999999999307220832633902318775653839111328125

Applying `HALF_UP` rounding rules to three places after the decimal point indeed yields `1.234` and not `1.235` as one would expect from reading the source code.

[1]: http://en.wikipedia.org/wiki/Double-precision_floating-point_format

**Comment by fommil** [comment]
@wrprice this is compounded by a bug in the Scala `BigDecimal` wrapper :smile: oh what joy. https://github.com/typelevel/scala/issues/95

It is kinda scary that Java 8 is broken for financial services and Java 7 is about to be EOLd. Almost makes a mockery of the whole "in life" concept.

**Comment by wrprice** [comment]
@fommil financial services applications [should not use floating-point][1] to represent currency.  That brokenness is on the application developers, not the language, and Java 7 was no different in this regard.  (The affected numbers may have changed, but the problems still existed.)

[1]: http://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

**Comment by fommil** [comment]
@wrprice BigDecimal rounding is broken, that's a big deal in financial services. This, in particular, affects displaying numbers on screens. So the current state of Java 8 is a really serious matter.

**Comment by wrprice** [comment]
@fommil Okay, I see what you're getting at.  Your original example was a primitive `double` and I thought that use was what you were referring to with your previous statement.  I agree that breaking `HALF_UP` and the lack of tests to catch it was egg on Java's face (hence this patch).  The good news is, they've added those missing tests.

Cheers.
